version: 2.0
jobs:
  build:
    docker:
      - image: clojure:lein-2.8.1
    working_directory: ~/clojars
    steps:
      - checkout
      - restore_cache:
          keys:
            - clojars-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: clojars-{{ checksum "project.clj" }}
      - run: lein do run -m user/migrate, test, uberjar
      - store_test_results:
          path: target/test-results
      - run: mv target/uberjar/clojars-web-*-standalone.jar clojars-uberjar.jar
      - store_artifacts:
          path: clojars-uberjar.jar
          destination: uberjar
